---
title: "Final Project"
author: "Huanyue Chen, Shi Zeng, Shengbin Jin"
date: "2023-04-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)
library(modelr)
library(ggplot2)
library(RSQLite)
library(caret)
library(plotROC)
```

## 1 Data Processing and Visualization

```{r}
data <- read_csv("nyts2022.csv")
#not using any tobacco: 19672 people
data_notuse <- data %>%
  filter(QN6 == 2 & QN35 ==2 & QN51 ==2 & QN62 == 2 & QN67 == 2 & QN79 == 2 & QN81 == 2 & QN84 == 2 & QN87 == 2)
data_notuse
# for those who uses e-cigaretts
#gender distribution
data_gender <- data %>%
  filter(QN6 == 1 & QN2!="NA") %>%
  count(QN2) %>%
  rename(gender = QN2, sum = n) 

data_gender

data_gender$gender <- str_replace(data_gender$gender, "1", "Male")
data_gender$gender <- str_replace(data_gender$gender, "2", "Female")


ggplot(data_gender, aes(x=gender, y=sum, fill = gender)) +
           geom_bar(stat = "identity") + 
  labs(title = "Gender distribution of e-cigarette users")

#age distribution
data_age <- data %>%
  filter(QN6 == 1 & QN1!="NA") %>%
  count(QN1) %>%
  rename(age = QN1, sum = n) %>%
  mutate(Age = age + 8) %>%
  select(-age)

data_age

data_age$Age<-as.factor(data_age$Age)

ggplot(data_age, aes(x=Age, y=sum)) +
           geom_bar(stat = "identity") +
  labs(title = "Age distribution of e-cigarette users")

#first usage
data_firstuse <- data %>%
  filter(QN6 == 1 & QN7!="NA") %>%
  count(QN7) %>%
  rename(first_age = QN7, sum = n) %>%
  mutate(first_Age = first_age + 7) %>%
  select(-first_age)

data_firstuse

data_firstuse$first_Age<-as.factor(data_firstuse$first_Age)

ggplot(data_firstuse, aes(x=first_Age, y=sum)) +
           geom_bar(stat = "identity") +
  labs(title = "First e-cigarette use age distribution")

# race 
data_race1 <- data %>%
  filter(QN6 == 1, QN5A == 1) %>%
  mutate(race = 'American Indian or Alaska Native') %>%
  select(newid, race)
data_race2 <- data %>%
  filter(QN6 == 1, QN5B == 1) %>%
  mutate(race = 'Asian') %>%
  select(newid, race)
data_race3 <- data %>%
  filter(QN6 == 1, QN5C == 1) %>%
  mutate(race = 'Black or African American') %>%
  select(newid, race)
data_race4 <- data %>%
  filter(QN6 == 1, QN5D == 1) %>%
  mutate(race = 'Native Hawaiian or Other Pacific Islander') %>%
  select(newid, race)
data_race5 <- data %>%
  filter(QN6 == 1, QN5E == 1) %>%
  mutate(race = 'White') %>%
  select(newid, race)
data_race6 <- data %>%
  filter(QN6 == 1, QN4B == 1 | QN4C == 1 | QN4D == 1 | QN4E == 1) %>%
  mutate(race = 'Hispanic, Latino, Latina, or of Spanish origin') %>%
  select(newid, race)

data_race <- data_race1 %>% 
  full_join(data_race2) %>% 
  full_join(data_race3) %>% 
  full_join(data_race4) %>% 
  full_join(data_race5) %>% 
  full_join(data_race6)

data_race <- data_race %>%
  count(race) %>%
  rename(sum = n)

data_race

ggplot(data_race, aes(x=race, y=sum)) +
           geom_bar(stat = "identity") +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +
  labs(title = "Race distribution of e-cigarette users")

# why first use
data_whyfirst <- data %>% 
  select(c('QN11A': 'QN11N')) %>%
           colSums(na.rm=TRUE)

data_whyfirst <- data.frame(data_whyfirst) %>%
    rename(sum = data_whyfirst)

row.names(data_whyfirst) <- c("From friend","From family","Try to quit using other tobacco products","Cost less","Easier to get","Seen people on TV, online, or in movies use them","Less harmful","Available in flavors","Could use them unnoticed at home or at school","Do tricks","Curious about them","Feeling anxious, stressed",
"To get a high or buzz from nicotine","other reason")

data_whyfirst <- cbind(reason = rownames(data_whyfirst), data_whyfirst)
rownames(data_whyfirst) <- NULL

data_whyfirst

ggplot(data_whyfirst, aes(x=reason, y=sum, fill = reason)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "Reason distribution of first use of e-cigarette")

# why current use
data_whycurrent <- data %>% 
  select(c('QN12A': 'QN12N')) %>%
           colSums(na.rm=TRUE)

data_whycurrent <- data.frame(data_whycurrent) %>%
    rename(sum = data_whycurrent)

row.names(data_whycurrent) <- c("From friend","From family","Try to quit using other tobacco products","Cost less","Easier to get","Seen people on TV, online, or in movies use them","Less harmful","Available in flavors","Could use them unnoticed at home or at school","Do tricks","Curious about them","Feeling anxious, stressed",
"To get a high or buzz from nicotine","other reason")
    
data_whycurrent <- cbind(reason = rownames(data_whycurrent), data_whycurrent)
rownames(data_whycurrent) <- NULL

data_whycurrent

ggplot(data_whycurrent, aes(x=reason, y=sum, fill = reason)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "Reason distribution of current use of e-cigarette")

# flavor
data_flavor <- data %>% 
  select(c('QN19AA': 'QN19AH')) %>%
           colSums(na.rm=TRUE)

data_flavor <- data.frame(data_flavor) %>%
    rename(sum = data_flavor)

row.names(data_flavor) <- c("Menthol", "Mint", "Clove or spice", "Fruit", "Chocolate", "Alcoholic drinks",
                                "Candy, desserts, or other sweets", "other flavor")
    
data_flavor <- cbind(flavor = rownames(data_flavor), data_flavor)
rownames(data_flavor) <- NULL

data_flavor

ggplot(data_flavor, aes(x=flavor, y=sum, fill = flavor)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "Flavor distribution of e-cigarette users")

#where to get
data_approach <- data %>% 
  filter(QN6 == 1) %>%
  select(c('QN21AA': 'QN21AL')) %>%
           colSums(na.rm=TRUE)

data_approach <- data.frame(data_approach) %>%
    rename(sum = data_approach)

row.names(data_approach) <- c("Did not buy", "From a person like friend, family member", "Gas station", "Grocery store",
                            "Drug store", "Mall or shopping center", "Vending machine", "Internet shopping", "Through the mail",
                            "Through a delivery service", "Vape shop or tobacco shop", "Other place")

data_approach <- cbind(where = rownames(data_approach), data_approach)
rownames(data_approach) <- NULL

data_approach

ggplot(data_approach, aes(x=where, y=sum, fill = where)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "Method of purchase distribution of e-cigarette users")

#how to quit
data_quit <- data %>% 
  select(c('QN28A': 'QN28J')) %>%
           colSums(na.rm=TRUE)

data_quit <- data.frame(data_quit) %>%
    rename(sum = data_quit)

row.names(data_quit) <- c("Did not use any resources", "Help or advice from a parent or caregiver", 
                          "Help or advice from a friend or peer", "Help or advice from a teacher or coach",
                          "Help or advice from a doctor or health care provider",
                          "Treatment from a hospital, medical center, or some other facility",
                          "Help or advice you found on the Internet", "A mobile app or texting program", 
                          "A telephone helpline or Quitline", "Something else")

data_quit <- cbind(how_to_quit = rownames(data_quit), data_quit)
rownames(data_quit) <- NULL

data_quit

ggplot(data_quit, aes(x=how_to_quit, y=sum, fill = how_to_quit)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "Way to try to quit using e-cigarette distribution")

# social media
data_media <- data %>% 
  select(c('QN135A': 'QN135H')) %>%
           colSums(na.rm=TRUE)

data_media <- data.frame(data_media) %>%
    rename(sum = data_media)

row.names(data_media) <- c("Facebook","Instagram","Snapchat","TikTok","Twitter","Reddit","YouTube",
                           "Some other site")
data_media <- cbind(social_media = rownames(data_media), data_media)
rownames(data_media) <- NULL

data_media

ggplot(data_media, aes(x=social_media, y=sum, fill = social_media)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "The distribution of social media with e-cigarette posts")

#who on social media post those
data_who <- data %>% 
  select(c('QN138A': 'QN138G')) %>%
           colSums(na.rm=TRUE)

data_who <- data.frame(data_who) %>%
    rename(sum = data_who)

row.names(data_who) <- c("People I know in real life","Online friends I have not met in real life","Celebrities or social media influencers","E-cigarette brands or sellers","Online news articles","Public health campaigns","Other")

data_who <- cbind(who = rownames(data_who), data_who)
rownames(data_who) <- NULL

data_who

ggplot(data_who, aes(x=who, y=sum, fill = who)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "The distribution of who usually post e-cigarettes in social media")

#who live with you are using tobacco?
data_whoUse <- data %>% 
  filter(QN6 == 1) %>%
  select(c('QN153A': 'QN153M')) %>%
           colSums(na.rm=TRUE)

data_whoUse <- data.frame(data_whoUse) %>%
    rename(sum = data_whoUse)

row.names(data_whoUse) <- c("E-cigarettes","Smoke cigarettes","Smoke cigars, cigarillos, or little cigars","Use chewing tobacco, snuff, or dip","Smoke tobacco in a hookah or waterpipe","Smoke roll-your-own cigarettes","Smoke pipes filled with tobacco", 
                            "Snus", "Use dissolvable tobacco products", "Smoke bidis", "Use heated tobacco products", 
                            "Use nicotine pouches", "No one who lives with me now uses any form of tobacco")

data_whoUse <- cbind(type = rownames(data_whoUse), data_whoUse)
rownames(data_whoUse) <- NULL

data_whoUse

ggplot(data_whoUse, aes(x=type, y=sum, fill = type)) +
           geom_bar(stat = "identity") +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  labs(title = "The distribution of type of tobacco use from people live with youth")

#grades in school
#the whole sample:
data_grade1 <- data %>% 
    filter(QN165 != "NA") %>%
    count(QN165) %>%
    rename(grade = QN165, sum = n)

data_grade1$grade <- str_replace(data_grade1$grade, "1", "Mostly A’s")
data_grade1$grade <- str_replace(data_grade1$grade, "2", "Mostly B’s")
data_grade1$grade <- str_replace(data_grade1$grade, "3", "Mostly C’s")
data_grade1$grade <- str_replace(data_grade1$grade, "4", "Mostly D’s")
data_grade1$grade <- str_replace(data_grade1$grade, "5", "Mostly E’s")
data_grade1$grade <- str_replace(data_grade1$grade, "6", "Mostly F’s")
data_grade1$grade <- str_replace(data_grade1$grade, "7", "Not sure")

data_grade1

ggplot(data_grade1, aes(x=grade, y=sum)) +
           geom_bar(stat = "identity") +
  labs(title = "Grade distribution of all youth during the past 1 year")

#who uses e-cigarettes:
data_grade2 <- data %>% 
    filter(QN6 == 1, QN165 != "NA") %>%
    count(QN165) %>%
    rename(grade = QN165, sum = n)

data_grade2$grade <- str_replace(data_grade2$grade, "1", "Mostly A’s")
data_grade2$grade <- str_replace(data_grade2$grade, "2", "Mostly B’s")
data_grade2$grade <- str_replace(data_grade2$grade, "3", "Mostly C’s")
data_grade2$grade <- str_replace(data_grade2$grade, "4", "Mostly D’s")
data_grade2$grade <- str_replace(data_grade2$grade, "5", "Mostly E’s")
data_grade2$grade <- str_replace(data_grade2$grade, "6", "Mostly F’s")
data_grade2$grade <- str_replace(data_grade2$grade, "7", "Not sure")

data_grade2

ggplot(data_grade2, aes(x=grade, y=sum)) +
           geom_bar(stat = "identity") +
  labs(title = "Grade distribution of tobacco users during the past 1 year")

#who do not use any tobacco:
data_grade3 <- data_notuse %>% 
    filter(QN165 != "NA") %>%
    count(QN165) %>%
    rename(grade = QN165, sum = n)

data_grade3$grade <- str_replace(data_grade3$grade, "1", "Mostly A’s")
data_grade3$grade <- str_replace(data_grade3$grade, "2", "Mostly B’s")
data_grade3$grade <- str_replace(data_grade3$grade, "3", "Mostly C’s")
data_grade3$grade <- str_replace(data_grade3$grade, "4", "Mostly D’s")
data_grade3$grade <- str_replace(data_grade3$grade, "5", "Mostly E’s")
data_grade3$grade <- str_replace(data_grade3$grade, "6", "Mostly F’s")
data_grade3$grade <- str_replace(data_grade3$grade, "7", "Not sure")

data_grade3

ggplot(data_grade3, aes(x=grade, y=sum)) +
           geom_bar(stat = "identity") +
  labs(title = "Grade distribution of youth that never user tobacco during the past 1 year")

#QN117: Do you believe that e-cigarettes are (LESS ADDICTIVE, EQUALLY ADDICTIVE, or MORE ADDICTIVE) than cigarettes?

```

## 2 Modeling
```{r}
data_use_model <- data %>%
  filter(QN6 == 1) %>% 
  mutate(use = 1)
data_notuse_model <- data %>%
  filter(QN6 == 2) %>% 
  mutate(use = 0)

data_model <- full_join(data_notuse_model, data_use_model)

data_model <- data_model %>% 
  filter(QN1 != 'NA' & QN2 != 'NA') %>%
  filter(QN4B == 1 | QN4C == 1 | QN4D == 1| QN4E == 1 | QN5A == 1 | QN5B == 1 | QN5C == 1 | QN5D == 1 | QN5E ==1) %>% rename(Mexican = QN4B, PuertoRican = QN4C, Cuban = QN4D, OtherSpanish = QN4E, AmericanIndian = QN5A, Asian = QN5B, Black = QN5C, Hawaiian = QN5D, White = QN5E)

data_model <- data_model %>% 
    mutate_if(is.numeric, ~replace_na(., 0)) %>%
    mutate(Gender = QN2 - 1) %>% #0 - male, 1 - female
    mutate(Age = QN1 + 8)

set.seed(1)
train <- createDataPartition(data_model$use, p=0.6, list=FALSE)

table(data_model$tobaccoUse[train])

data_train <- data_model[as.integer(train),]
data_test <- data_model[-as.integer(train),]

fit <- glm(use ~ Age + Gender + Mexican + PuertoRican + Cuban + OtherSpanish + AmericanIndian + Asian + Black + Hawaiian + White, data=data_train, family=binomial(link="logit"))

summary(fit)
```

# Model evaluation
```{r}
#prediction
prob <- predict(fit, newdata=data_test, type="response")
#"response" means the actual probability, after applying the logistic function

pred <- ifelse(prob > 0.5, 1, 0)

hist(prob)

#calculate accuracy
mean(pred == data_test$use, na.rm=TRUE)

#confusion matrix
table(pred, data_test$use)

#sensitivity
sensitivity <- 46 / (46 + 2223) # 0.0203
#specificity
specificity <- 8729 / (8729 + 66) # 0.9925
#recall
recall <- 46 / (46 + 2223) # 0.0203
#precision
precision <- 46 / (46 + 66) # 0.4107
#F1 score
F1 <- 2 * (precision * recall) / (precision + recall) #0.03864

#plot ROC curve
g <- data_test %>%
  add_predictions(fit, type="response") %>%
  ggplot(aes(m=pred, d=use)) +
  geom_roc() +
  style_roc()

auc <- round((calc_auc(g))$AUC, 4)

g + annotate("text", x=0.75, y=0.25, label=paste("AUC =", auc))
```